# Generated by Django 3.0.7 on 2020-06-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_auto_20200624_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_file',
            new_name='docfile',
        ),
    ]
